
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/application.rb'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/spring'
    - 'config/initializers/assets.rb'
    - 'bin/setup'
    - 'config/**/*'
    - 'config.ru'
    - 'db/migrate/20150929184523_devise_create_users.rb'
    - 'Rakefile'

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/LineLength:
  Max: 120

