language: ruby
rvm:
  - 2.3.0
sudo: false
addons:
  postgresql: "9.3"
script:
  - psql -c 'create database portfolio_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
bundler_args: "--binstubs=./bundler_stubs"
deploy:
  provider: heroku
  api_key:
    secure: k+JGXOu76Fwc99j84tPVHA4VIBhieUWQ6WyqE+CH57VIloTuhDAwudQU3sRFcEHTYY0sYqn/lE10k1Ono0RnxCYT9l9QjpEn/re6dWMTESdIe+FuwGSxntXbbAdQC7qnwoxUydzgeWLmdKZY+G0t5LtdCBUSKt6oA8NK2c4sw0s=
  app: nbarnes-blog
  on:
    repo: nbarnes/portfolio
  run:
    - rake db:migrate
