
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: portfolio/dev

test:
  <<: *default
  database: portfolio/test

production:
  <<: *default
  database: portfolio/prod
